### ISSUE TITLE
Rendez-vous 17/01/17

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/VignalEnChanson#24]
- [x] Navbar : 
  - [x] supprimer le logo texte
  - [x] mettre à jour les textes

- [x] Header :
  - [x] Prendre en compte la demande de Bernard au niveau du titre. Plus de "Bienvenue".
  - [x] afficher l'extrait de la chanson en entier si possible sur tous les formats.

- [x] Présentation de l'équipe :
  - [x] taille "desktop" : on prend l'image du groupe (2.jpg) avec des infos bulles affichés sur action du visiteur. les bulles sont affichées sur l'image directement sur le fond. Pas de popup. ***Seulement si le temps est dispo car réalisation plus complexe et consommatrice de temps***
  - [x] taille "tablette": on prend l'image du groupe (2.jpg) avec des infos bulles affichés pour chaque personne avec action du visiteur. les bulles sont affichées sous forme de popup. 
  - [x] taille "smartphone" : on garde l'existant donc rien à faire.
  - [x] Recherche l'icône "bulle de dialogue BD" ==> fa-comment

- [x] Section "Extraits" (ex-Music) : 
  - [x] colonne 1 : youtube embeded video + mp3 player
  - [ ] colonne 2 : 2 images restantes de la galerie photos

- [x]  Section "Scolaire"
  - [x] fond "dessin enfant"
  - [x] en haut à gauche : descriptif
  - [x] en bas à droite : lien Google

- [x] Formulaire de contact => comme puzzlout portal. Pas de formulaire pour commencer. Ouverture via lien "mailto". Prévoir la sécurisation de l'email de contact (Recaptcha + email dans fichier php).
