### ISSUE TITLE
Remarques de l'email du 10/02/17

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/VignalEnChanson#71]
- [x] problème de playback dans les extraits

- [x] Médaillons :
  - [x] texte plus grand sur petit écran pour la fonction
  - [x] couleur pour les fonctions (Manu: Bleu ; Cécile: Or ; Muriel : Orange ; Bernard : Vert)

- [x] Contact : mettre l'image d'enfant en fond.
- [ ] Envoyer à Bernard les textes pour :
